[FEATURE] Add option -r/--regex to find (#3083)
* [FEATURE] Add option -r/--regex to find

If the option -r/--regex is supplied to 'gopass find', the argument is treated
as a regex pattern instead of a substring.

Signed-off-by: Carl Smedstad <carl.smedstad@protonmail.com>

* [UX] Fail and produce error message when bad regex supplied to find -r

For example:

    $ ./gopass find -r 'mystring['

    Error: error parsing regexp: missing closing ]: `[`

Signed-off-by: Carl Smedstad <carl.smedstad@protonmail.com>

* [CLEANUP] Rename argument regex to reMatch

* [CLEANUP] Compile regex outside of loop

---------

Signed-off-by: Carl Smedstad <carl.smedstad@protonmail.com>